### ISSUE TITLE
Cannot startup with provided README

### ISSUE THREAD

**Issue by chris-aeviator** [dhax/go-base-vue#1]
Hi and thanks for your repository. I'm trying to run your application, however it makes a request to `localhost:3000` defined by then env https://github.com/dhax/go-base-vue/blob/e601e49c9db45f4b8c2820d9e9069c296ff7a988/.env#L1

What's the server implementation the vue-app is talking to?

EDIT: ok – when starting the app with `PORT=3000` I can get the app running without any issues, however, it would benefit from a detailed README.md, I enter my email and I am not able to proceed

```
[HMR] Waiting for update signal from WDS... log.js:24
AUTH_INIT auth.module.js:51
send token Login.vue:108
AUTH_TOKEN_REQUEST auth.module.js:150
AUTH_ERROR auth.module.js:181
```

```
payload:Object
errorCode:404
errorMessage:undefined
type:"AUTH_ERROR"

```

**Comment by chris-aeviator** [comment]
I found out about your`go-base` repo :)

**Comment by dhax** [comment]
Hi, yes I should make it clear in the readme that this is just a Demo Application for a specific server, i.e. gitHub.com/dhax/go-base
