### ISSUE TITLE
CORS policy prevents request

### ISSUE THREAD

**Issue by tcurdt** [dhax/go-base-vue#2]
With the instructions given the CORS policy prevents the connection.

`Access to XMLHttpRequest at 'http://localhost:3000/auth/login' from origin 'http://localhost:8080' has been blocked by CORS policy:`

**Comment by dhax** [comment]
Hi,
are you running the go-base server with CORS enabled? I.e. when starting the server set the following environment variable to enable CORS requests (defaults to false):

ENABLE_CORS=true

**Comment by tcurdt** [comment]
I was just following the instructions.
IIRC I later even tried `ENABLE_CORS=false` explicitly.

**Comment by dhax** [comment]
have you also tried with ENABLE_CORS=**true**  ? Above you said you tried explicitly with false, but false is already the default...

Just testet it locally and it works for me.

**Comment by tcurdt** [comment]
> have you also tried with ENABLE_CORS=true ?

TBH I cannot remember :)

You tested it successfully with CORS being **true** or **false**?

**Comment by dhax** [comment]
If you build the client into the server's public folder, the server will serve the client on port 3000, then CORS can stay disabled (current default) (see server api/api.go Line 86 to end).

But if you run the client during dev, i.e. serving from localhost:8080, then you need to enable CORS on the server by setting ENABLE_CORS=true in the server's env variables:

`ENABLE_CORS=true go run main.go serve`

maybe I should enable CORS by default...

**Comment by tcurdt** [comment]
According to the error message I was running the frontend on 8080 trying to reach the API at 3000.
So I guess I did not try the `ENABLE_CORS=true`.

Anyway!
Maybe add the information to the README?
Although it seems rather obvious reading it now, it certainly would have helped me at the time.

**Comment by dhax** [comment]
yeah, I will add something like above to the server's readme. Thanks for the feedback!

I will close this for now, feel free to reopen or comment if you have further questions.
